logging:
  level:
    org:
      zalando:
        logbook: TRACE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/filmsdb
    username: dbuser
    password: 12345
    driver-class-name: org.postgresql.Driver